notifications:
    email: false
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - pip install --upgrade pip setuptools
    - pip install -r dev-requirements.txt
    - pip install -r requirements.txt
    - pip install cython ; python_version==3.6
    - pip install -e .
    - pip list
before_script: flake8 civismlext
script:
    - py.test -vv civismlext
