notifications:
    email: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install --upgrade pip setuptools
    - pip install -r dev-requirements.txt
    - pip install -r requirements.txt
    - pip install pandas==0.19 ; python_version==3.5
    - pip install -e .
before_script: flake8 civismlext
script:
    - py.test -vv civismlext
